[build]
  command = "yarn run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
