# yaml-languale-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: jingjing-note/NotionNext
  branch: main
  commit_messages:
    context: "Sveltia CMS"

media_folder: public/images
public_folder: /images

site_url: https://jingjingnote.cn

local_backend: false